### PR TITLE
thread limit per request

### PR DESCRIPTION
**Pull request by remicollet**
Seems this have to be in RINIT, not in MINIT.

### CODE REVIEW

**Comment by remicollet** [comment]
Notice, I still think that `set_single_thread` default should be 1.

BTW, running test suite with set_single_thread=1 and shutdown_sleep_count=0, I still encounter segfault in 073_Imagick_forwardFourierTransformImage_basic.phpt and 086_Imagick_forwardFourierTransformImage_basic.phpt, during the skip check, looks like thread limit is not honoured there... :(

**Comment by remicollet** [comment]
OK, found why the segfault, INI setting are not honoured during SKIP execution.... (PHP issue)

**Comment by mkoppanen** [comment]
Is this related to https://github.com/Imagick/imagick/pull/348 or separate?

**Comment by remicollet** [comment]
This  is something different

**Comment by remicollet** [comment]
This PR is about when to set the option.

Better to set it per request, as user may change its value, so it should only apply to the current request.

The other PR is about changing the default value.

**Comment by Danack** [comment]
Ugh.

> so it should only apply to the current request.

But I don't think it will. Consider the scenario:

Request 1: a) init, b) set thread limit 4, c) download image from remote site d) start image processing.
Request 2: a) init

If 2a occurs between 1b and 1d, then the thread limit will be not what the user is expecting.

This is a recurring pit of sadness.

I'm hungry, so going to make and eat food, but I'm tempted to just make it so that Imagick in only ever uses one thread. It's just kind of insane to have a shared C library that tweak how many threads are running, when it's running in something else that is already threaded.

If people want to optmize image processing using multiple threads, they can and should pass that work off to background workers.

**Comment by Danack** [comment]
> I'm hungry, so going to make and eat food, 

Status update, food has been eaten, and this is still giving me a headache.

Unless someone can persuade me otherwise, I think tomorrow I'll add some: 

```
strcmp(sapi_module.name, "cli")
```

in various places, to disable being able to use more than one thread in any sapi other than the CLI one.

**Comment by remicollet** [comment]
> If 2a occurs between 1b and 1d, then the thread limit will be not what the user is expecting.

Only in ZTS mode, right ?
At least this solves the issue in NTS build which is used in most case (mod_php or php-fpm)

**Comment by Danack** [comment]
Thanks merged via git in 3de6f0cf65767219f762337e46081e99ab8a334f

**Pull request closed without merging**
