### PR TITLE
call omp_pause_resource_all when available

### PR DESCRIPTION
**Pull request by remicollet**
From @rlerdorf work on gmagick

### CODE REVIEW

**Comment by Danack** [comment]
Can you say which OS this can be tested on? When I looked last there didn't seem to be any standard distributions that had this available.

**Comment by rlerdorf** [comment]
It was added in gcc-9.2.
I am on Debian bullseye/sid with gcc-10.2.1 but Fedora 32 and 33, Arch Current, Gentoo Stable, Manjaro 19 and 20, OpenSuse Tumbleweed, and Suse Enterprise 15 all have at least gcc-9.2 with a number of them on gcc-10.

**Comment by rlerdorf** [comment]
Just to make sure since I had only tested it with gcc-10, I spun up an Ubuntu 20.04 LTS which has `gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)` and it detected `omp_pause_resource_all()` correctly.

**Comment by remicollet** [comment]
I also test with GCC 8 (on RHEL-8).
Library have the function but not in public header (so is not used with this code)

**Comment by Danack** [comment]
This was merged via git in f10d52cf1144b75451e6829bc317d99866dd731d and 700a58adf9a24a35fbad7dfcc43e62ad4e5d23de

**Comment by Danack** [comment]
I'll have to setup a local environment to be able to reproduce test this locally, but @remicollet any clue about why this change appears to make things fail? Reverting the clean shutdown in cf51ea81a333e10eef590ffbdc5816be3bd69750 seems to make the CI pass.

**Comment by remicollet** [comment]
> why this change appears to make things fail? 

Sorry, no idea on what happen on CI

I run often (at least weekly) the test suite with this patch applied and everything passes

This morning I run another set of build s
- Fedora 32, 33 and 34, RHEL 7.9 and 8.4
- With PR #346 #347 #348 #350 and #375 (or without #348 which set set_single_thread = 1 by default)
- With PR #346 #347 #350 and #375
- With PH P7.4 and 8.0

Test suite passes everywhere

**Comment by remicollet** [comment]
@Danack CI seems ok with type fixed in d507dd74ee46ca8db0b659e4151f5e5440056aca

**Comment by Danack** [comment]
I guess I should have tested it locally with an appropriate version of GCC. Do you have any advice on how to get ImageMagick to have fonts in the repro container I added in https://github.com/Imagick/imagick/tree/repro_container

It seems that ImageMagick is failing to find the fontconfig program despite it being installed.

```
configure:26314: checking for fontconfig >= 2.1.0
configure:26321: $PKG_CONFIG --exists --print-errors "fontconfig >= 2.1.0"
Package fontconfig was not found in the pkg-config search path.
Perhaps you should add the directory containing `fontconfig.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fontconfig' found
configure:26324: $? = 1
configure:26338: $PKG_CONFIG --exists --print-errors "fontconfig >= 2.1.0"
Package fontconfig was not found in the pkg-config search path.
Perhaps you should add the directory containing `fontconfig.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fontconfig' found
configure:26341: $? = 1
configure:26355: result: no
No package 'fontconfig' found
```

Also, it seems that ImageMagick is looking for 'afm' files rather than 'otf' files when checking the urw-base35 directory:

```
stat("/usr/share/fonts/opentype/urw-base35/URWGothic-Book.afm", 0x7ffd73f3fd90) = -1 ENOENT (No such file or directory)
stat("/usr/local/etc/ImageMagick-7//usr/share/fonts/opentype/urw-base35/URWGothic-Book.afm", 0x7ffd73f3fd90) = -1 ENOENT (No such file or directory)
stat("/usr/share/fonts/opentype/urw-base35/URWGothic-BookOblique.afm", 0x7ffd73f3fd90) = -1 ENOENT (No such file or directory)
stat("/usr/local/etc/ImageMagick-7//usr/share/fonts/opentype/urw-base35/URWGothic-BookOblique.afm", 0x7ffd73f3fd90) = -1 ENOENT (No such file or directory)
```

Which feels a lot like:

SideShowBobRakes

**Comment by Danack** [comment]
So, kind of weird that it didn't give a useful error message in CI....but seems to be working now. I'll have to figure out the fonts another day.

**Pull request closed without merging**
