### PR TITLE
Return empty string instead of NULL

### PR DESCRIPTION
**Pull request by negram**
The signature of the function tells us that getImageBlob() always returns a string or throws Exception.

In this case, the returning value is NULL as retval is unset.

### CODE REVIEW

**Comment by negram** [comment]
I'm actually not sure what exactly we should do here, it looks like we probably must throw an exception.
There is [the comment](https://www.php.net/manual/en/imagick.getimageblob) in the documentation that the function sometimes returns an empty string, that's why I used this value.

Provably, we can convert it to the exception - what do you think?

Noticed this when running tests:
```shell
$ cat tests/325_Imagick_setDepth.out
Depth is 16

Fatal error: Imagick::getImageBlob(): Return value must be of type string, null returned in Unknown on line 0%
```

**Comment by Danack** [comment]
It should definitely throw an exception, as no-one's going to be checking for empty string.

If you feel like implementing it, I [wrote a test for it](https://github.com/Imagick/imagick/blob/image_blob_exceptions/tests/329_imagick_getImageBlob_empty.phpt) in 
the https://github.com/Imagick/imagick/tree/image_blob_exceptions branch.

**Comment by negram** [comment]
Sure, I'll do it tomorrow (or today evening)

**Comment by negram** [comment]
Added the exception

**Comment by negram** [comment]
ouch, I rebased the branch on top of the [image_blob_exceptions](https://github.com/Imagick/imagick/tree/image_blob_exceptions) and got much more changes than expected. Shall I re-do the pull-request into that branch?

**Comment by Danack** [comment]
I should have said earlier.....the way I work is to develop against the develop branch. If in general you branch from there, it should be easier.

I leave the master branch alone most of the time. There are people who have production systems that pull it in to build against (which tbh gives me the heeby-jeebies), so to avoid having urgent issues needing fixing, I tend not to merge to it until I know that I'm going to be able to be at a computer to at least be able to respond to those issues.

Also, I don't use github's tools for merging - except for trivial stuff. I always pull branches down to my computer, so that I can review them easily. So if there's ever a commit that's been done on a 'wrong' branch, don't worry about moving it to another branch. I can almost always cherry-pick the change onto a branch where it can be merged easily.

btw, would it be possible for you to drop me an email at danack@basreality.com, so I can say thanks via a non-public medium.

**Comment by negram** [comment]
Opened #606 instead, that one is against "develop".
actually, I could've noticed this earlier :)

**Pull request closed without merging**
