### PR TITLE
Use RETURN_THROWS() to highlight that we have raised an exception

### PR DESCRIPTION
**Pull request by negram**
`RETURN_THROWS()` slightly improves the readability of the code and adds some checks that verify that an exception was indeed thrown where it was expected.

There are many similar places, I just updated the ones I noticed when dealing with problems. If you'd like, I can update others as well.

If you feel like the change isn't worth doing, let me know - we can just close it :)

### CODE REVIEW

**Comment by Danack** [comment]
true_neutral

Doesn't appear to be any harm. It would be nice if there was a way to enforce it as a code-style, but I can't think of a trivial way to do it.

Merged in ed1e960d32ef2a415fe4ad6456f73d4a600cd5c7

**Comment by Danack** [comment]
Ah. RETURN_THROWS seems to be invalid on [PHP 5.6 to 7.4](https://github.com/Imagick/imagick/actions/runs/4316435104) which will need to be looked at.

**Comment by negram** [comment]
Added define for those versions: https://github.com/Imagick/imagick/pull/587/files#diff-445939060ca478914e1faf72fba2c91526525dd5eb3981b2a9b85da43e45cb57R50
```c
/* RETURN_THROWS() isn't defined in PHP 5.6 through 7.4
 */
#if !defined(RETURN_THROWS)
#define RETURN_THROWS() return
#endif
```

**Comment by Danack** [comment]
Thanks. 

Ah, it looks like you force-pushed to the branch, which is slightly inconvenient as the previous change was already merged into develop.

Do you mind if I just add the 4 lines necessary with an attribution in the commit message? Or otherwise, can you do a clean PR against develop of just the 4 lines for the define?

**Comment by negram** [comment]
Yeah, sure. If you can add them, that would be great (i think, that's how we reduce the number of steps :) )!

**Comment by Danack** [comment]
Cool thanks.

**Pull request closed without merging**
