### PR TITLE
Fix broken test - sin()/cos() accept argument in radians

### PR DESCRIPTION
**Pull request by andypost**
Ref https://www.php.net/manual/en/function.cos.php

### CODE REVIEW

**Comment by Danack** [comment]
Thanks. I will merge this, but would prefer to also make the test actually detect it works correctly e.g. by drawing a horizontal line, then rotating the image and checking the line is where it should be.

**Comment by andypost** [comment]
> checking the line is where it should be.

Nice idea! I will try to dig how to find a line in image

**Comment by andypost** [comment]
@Danack I hev no idea where to file PR but example in docs needs fix too https://www.php.net/manual/en/imagick.affinetransformimage.php

**Comment by Danack** [comment]
https://github.com/php/doc-en is where docs PRs can be sent....it does need better documentation for the flow, but it's just XML that can be edited by hand.

**Comment by Danack** [comment]
Thanks. This was merged via git.

**Pull request closed without merging**
