### PR TITLE
Houghline

### PR DESCRIPTION
**Pull request by Narayanabelur**
Added PHP extension to Hough line Image

### CODE REVIEW

**Comment by Danack** [comment]
Thanks, looks good.

Please could you add a small example input image (preferably png) that isn't subject to someone else's copyright?

**Comment by Narayanabelur** [comment]
Great, is it under 'test' folder ?

**Comment by Danack** [comment]
Yep.

Doesn't have to be a big or complicated example, it's for:

* making it easy for me to make a demo for it.
* making it so I can run valgrind against the code, which is a tool that helps check if there are any invalid memory accesses.

**Comment by Narayanabelur** [comment]
Got it thanks. 
Placed input image  'houghline_input_image.png' under 'tests' folder and updated '281_imagick_houghLineImage_basic.phpt' script. Cheers.

**Comment by Danack** [comment]
Apologies for leaving it open for so long. This was merged and is going to be in the next release.

**Pull request closed without merging**
