### PR TITLE
Fix missing files for tests

### PR DESCRIPTION
**Pull request by andypost**
Used to try build the extension for Alpinelinux and found that few files are missing at PECL uploaded package

For details there's https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/22343/pipelines

### CODE REVIEW

**Comment by andypost** [comment]
Diff for missing files could be found at https://gitlab.alpinelinux.org/alpine/aports/-/jobs/415350

**Review by glensc — APPROVED** [review]

**Comment by Danack** [comment]
Thanks. 

I can't see the details - what command is it you're running to get a failure from these missing? I should add a similar test in this repo.

**Comment by andypost** [comment]
Thank you! I'm using following command
`make NO_INTERACTION=1 REPORT_EXIT_STATUS=1 test TESTS=--show-diff` the `TESTS=--show-diff` helps to catch this missing files, for example

```
TEST 261/286 [tests/274_imagick_setImageAlpha.phpt]
========DIFF========
001+ Warning: require_once(/builds/alpine/aports/community/php7-pecl-imagick/src/imagick-3.5.0RC1/tests/../util/functions.php): failed to open stream: No such file or directory in /builds/alpine/aports/community/php7-pecl-imagick/src/imagick-3.5.0RC1/tests/274_imagick_setImageAlpha.php on line 3
001- Ok
002+ 
003+ Fatal error: require_once(): Failed opening required '/builds/alpine/aports/community/php7-pecl-imagick/src/imagick-3.5.0RC1/tests/../util/functions.php' (include_path='.:/usr/share/php7') in /builds/alpine/aports/community/php7-pecl-imagick/src/imagick-3.5.0RC1/tests/274_imagick_setImageAlpha.php on line 3

...
TEST 277/286 [tests/289_Imagick_setImageMask_basic.phpt]
========DIFF========
001+ Fatal error: Uncaught ImagickException: unable to open image '/builds/alpine/aports/community/php7-pecl-imagick/src/imagick-3.5.0RC1/tests/houghline_input_image.png': No such file or directory @ error/blob.c/OpenBlob/3537 in /builds/alpine/aports/community/php7-pecl-imagick/src/imagick-3.5.0RC1/tests/289_Imagick_setImageMask_basic.php:3
```

**Comment by Danack** [comment]
Okay thanks. Merged via git.

I made an issue to remind myself #422

**Pull request merged**
