### PR TITLE
Fix nullable in Imagick.stub.php

### PR DESCRIPTION
**Pull request by mvorisek**
CI build error:
```
Imagick::newImage(): Parameter format has null default, but is not nullable
make: *** [Makefile:195: /tmp/pear/temp/imagick/Imagick_arginfo.h] Error 1
```

### CODE REVIEW

**Comment by mvorisek** [comment]
`regen_arginfo.sh` needs to be probably rerun before merging - please approve CI for me

**Comment by mvorisek** [comment]
@Danack can I ask you to merge this PR in order to support PHP 8.4/php-src master?

**Comment by Danack** [comment]
Thanks. I also added a test and fixed the parameter parsing which needed tweaking.

I also fixed another one that showed up in ImagickKernel::fromMatrix.

I'm going to leave the numbers in the YML for the moment for reasons.

btw, if you have time to look at https://github.com/Imagick/imagick/issues/679 it would be appreciated.

**Comment by mvorisek** [comment]
> I'm going to leave the numbers in the YML for the moment for reasons.

May I know your concerns?

The numbers in YML must be escaped in quotes otherwise version like `8.0` is parsed as floating point number instead of string which converts such value (when casted back to a string) into `8` string which is unwanted.

Example:

image

**Comment by mvorisek** [comment]
Feel free to use my https://github.com/mvorisek/image-php Docker images. There are built every 2 weeks with a lot of extensions - https://github.com/mvorisek/image-php/blob/master/test.php incl. this one.

**Pull request closed without merging**
