### PR TITLE
Minor update to README.md

### PR DESCRIPTION
**Pull request by mkoppanen**
Correct the link URL

### CODE REVIEW

**Comment by Danack** [comment]
Thanks.

We still need to meet for a beer at some point, when it is legal to do so....

**Comment by mkoppanen** [comment]
@Danack sure thing! hospitality should open in restricted way 1 July (fingers crossed)

**Comment by Danack** [comment]
actually, as you're here....

@mkoppanen fyi, I'm planning to ask companies to start contributing cash-money if they use this project, as although it does useful stuff, I kind of don't enjoy supporting it that much, but do enjoy things like eating food and having a roof over my head....

If you care about how that is done, maybe watch the words I add to the repo or on phpimagick.com 

It's just quite frustrating that if every company that used the library paid $1 a year for it.....that would make it more than fully funded....

**Comment by mkoppanen** [comment]
@Danack,

you have been doing most of the maintenance for the past years, so I am happy with people / companies giving donations. The hours spent on reproducing bugs, debugging issues etc are not free in terms that it's time taken away from something else. 

No need to worry about me on the wording, I am sure it's something sensible.

**Pull request merged**
